### ISSUE TITLE
OpenBLAS and NUM_THREADS

### ISSUE THREAD

**Issue by dineshbvadhia** [jakirkham/nanshe#250]
OpenBLAS detects the number of cores at runtime but the actual number cores used are determined by NUM_THREADS. If NUM_THREADS is to set to a high number during compilation then there is a good chance that all cores will be used. Eg. if NUM_THREADS = 128 then most multi-core machines will be covered.  

Has OpenBLAS been compiled with a large NUM_THREADS?

**Comment by jakirkham** [comment]
This issue was moved to jakirkham/nanshe-build#7
